### ISSUE TITLE
vercel部署问题

### ISSUE THREAD

**Issue by ynsdfz36** [Yuzi0201/Yuzi0201.github.io#2]
使用vercel部署评论系统的时候，显示我的账号被locked了，请问一下能否使用不同GitHub账号登陆的vercel部署另一个GitHub的网页

**Comment by YuziO2** [comment]
不是很明白描述，vercel部署了评论系统后，你可以给vercel页面绑定自己的域名，也可以直接使用vercel的域名，把网址直接填进waline配置就行了。

**Comment by ynsdfz36** [comment]
感谢，已经布置好了，请问一下，我的评论系统如果是用境内网就会显示Failed to fetch，只有连外网时才能正常发评论，且国内连已经发布的评论也看不见，请问如何解决

**Comment by YuziO2** [comment]
> 感谢，已经布置好了，请问一下，我的评论系统如果是用境内网就会显示Failed to fetch，只有连外网时才能正常发评论，且国内连已经发布的评论也看不见，请问如何解决

用cloudflare代理一下吧，vercel在国内基本被屏蔽了

**Comment by ynsdfz36** [comment]
我看了一下您的博客，国内是可以评论的，请问一下怎么用cloudflare代理

**Comment by YuziO2** [comment]
> 我看了一下您的博客，国内是可以评论的，请问一下怎么用cloudflare代理

可以Google搜一下，挺简单的😉

**Comment by ynsdfz36** [comment]
cloudflare代理整个网页吗，还是说只代理评论那个，网站访问的话现在没有问题

**Comment by YuziO2** [comment]
> cloudflare代理整个网页吗，还是说只代理评论那个，网站访问的话现在没有问题

网页没问题的话就只代理评论咯

**Comment by ynsdfz36** [comment]
怎么单独代理评论啊（实在抱歉，电脑小白一个）

**Comment by YuziO2** [comment]
> 怎么单独代理评论啊（实在抱歉，电脑小白一个）

有自己的域名吗？按照waline的教程加到vercel的自定义域名里，再在cf的dashboard里设置域名的指向，然后把橙色开关打开即可

**Comment by TsumugiMirai** [comment]
非常感谢

**Comment by TsumugiMirai** [comment]
大佬可以留一个联系方式吗，实在有些问题解决不了

**Comment by YuziO2** [comment]
> 大佬可以留一个联系方式吗，实在有些问题解决不了

邮箱联系即可，我会及时回复

**Comment by TsumugiMirai** [comment]
已发送邮箱，非常感谢
